resilience4j:
 circuitbreaker:
  instances:
    paymentService:
     failureRateThreshold: 50
     ringBufferSizeInClosedState: 6
     ringBufferSizeInHalfOpenState: 3
     waitDurationInOpenState: 60s
     automaticTransitionFromOpenToHalfOpenEnabled: true